version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"

    volumes:
      - ./client:/app
    
    networks:
      - lms-network
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    depends_on:
      - client  
    networks:
      - lms-network


networks:
  lms-network:
    driver: bridge
