services:
  frontend:
    build: ./client
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Use the bridge network driver for communication
