FROM node:18-alpine AS build

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the application files
COPY . .

# Expose the backend port (e.g., 3000)
EXPOSE 5000

# Start the backend
CMD ["npm", "start"]
